{
 "title": "FIS-Bc",
 "description": "Ukázkový dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "MVE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Celkový výkon",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: -20s)\r\n  |> filter(fn: (r) =>\r\n    r.tag2 == \"vykon\"\r\n  )"
    }
   ]
  },
  {
   "title": "Průměrný výkon",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: 2021-12-01T00:00:00Z)\r\n  |> filter(fn: (r) =>\r\n    r.tag2 == \"vykon\"\r\n  )\r\n  |> mean()"
    }
   ]
  },
  {
   "title": "Kumulativní výroba",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: 2021-12-01T00:00:00Z)\r\n  |> filter(fn: (r) =>\r\n    r.tag2 == \"vykon\"\r\n  )\r\n  |> aggregateWindow(every: 1h, fn: mean)"
    }
   ]
  },
  { "title": "Upozornění", "type": "alertlist", "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 } },
  { "title": "Aktuální stav TG1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Výkon TG1",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: -20s)\r\n  |> filter(fn: (r) =>\r\n    r.tag1 == \"TG1\" and\r\n    r.tag2 == \"vykon\"\r\n  )"
    }
   ]
  },
  {
   "title": "Hladina nad TG1",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: -20s)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"merHladiny1\" and\r\n    r.tag1 == \"TG1\" and\r\n    r.tag2 == \"hladina\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "Hladina pod TG1",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: -20s)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"merHladiny2\" and\r\n    r.tag1 == \"TG1\" and\r\n    r.tag2 == \"hladina\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "Teplota ložiska generátoru TG1",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: -20s)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"merTeploty1\" and\r\n    r.tag1 == \"TG1\" and\r\n    r.tag2 == \"teplota\"\r\n  )"
    }
   ]
  },
  {
   "title": "Teplota ložiska turbíny TG1",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: -20s)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"merTeploty2\" and\r\n    r.tag1 == \"TG1\" and\r\n    r.tag2 == \"teplota\"\r\n  )"
    }
   ]
  },
  { "title": "Aktuální stav TG2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Výkon TG2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: -20s)\r\n  |> filter(fn: (r) =>\r\n    r.tag1 == \"TG2\" and\r\n    r.tag2 == \"vykon\"\r\n  )"
    }
   ]
  },
  {
   "title": "Hladina nad TG2",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: -20s)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"merHladiny3\" and\r\n    r.tag1 == \"TG2\" and\r\n    r.tag2 == \"hladina\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "Hladina pod TG2",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: -20s)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"merHladiny4\" and\r\n    r.tag1 == \"TG2\" and\r\n    r.tag2 == \"hladina\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "Teplota ložiska generátoru TG2",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: -20s)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"merTeploty3\" and\r\n    r.tag1 == \"TG2\" and\r\n    r.tag2 == \"teplota\"\r\n  )"
    }
   ]
  },
  {
   "title": "Teplota ložiska turbíny TG2",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: -20s)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"merTeploty4\" and\r\n    r.tag1 == \"TG2\" and\r\n    r.tag2 == \"teplota\"\r\n  )"
    }
   ]
  },
  {
   "title": "Dlouhodobý přehled",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true
  },
  {
   "title": "Výkon",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: 2021-12-01T00:00:00Z)\r\n  |> filter(fn: (r) =>\r\n    r.tag2 == \"vykon\"\r\n  )"
    }
   ]
  },
  {
   "title": "Hladina",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: 2021-01-01T00:00:00Z)\r\n  |> filter(fn: (r) =>\r\n    r.tag2 == \"hladina\"\r\n  )"
    }
   ]
  },
  {
   "title": "Průměrná hladina nad MVE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: 2021-01-01T00:00:00Z)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"merHladiny1\" or\r\n    r._measurement == \"merHladiny3\"\r\n  )"
    }
   ]
  },
  {
   "title": "Průměrná hladina pod MVE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: 2021-01-01T00:00:00Z)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"merHladiny2\" or\r\n    r._measurement == \"merHladiny4\"\r\n  )"
    }
   ]
  },
  {
   "title": "Teplota ložisek",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket:\"mve\")\r\n  |> range(start: 2021-12-01T00:00:00Z)\r\n  |> filter(fn: (r) =>\r\n    r.tag2 == \"teplota\"\r\n  )"
    }
   ]
  }
 ]
}